import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface MealData {
  id: number;
  name: string;
  mealType: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  createdAt: string;
}

interface NutritionStats {
  averages: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
  };
  goals: {
    dailyCalories: number;
    dailyProtein: number;
    dailyCarbs: number;
    dailyFat: number;
  };
  achievement: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
  };
}

export const generateNutritionPDF = (
  meals: MealData[],
  stats: NutritionStats,
  timeRange: string,
  userName: string = 'User'
) => {
  const doc = new jsPDF();
  
  // Page settings
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  
  // Title
  doc.setFontSize(24);
  doc.setTextColor(20, 82, 89); // Teal color
  doc.text('FitBuddy Nutrition Report', margin, 25);
  
  // Date and user info
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, 35);
  doc.text(`Period: ${timeRange}`, margin, 40);
  doc.text(`User: ${userName}`, margin, 45);
  
  // Summary section
  let yPos = 60;
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Summary Statistics', margin, yPos);
  
  yPos += 10;
  
  // Create summary table
  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Average', 'Goal', 'Achievement']],
    body: [
      [
        'Calories (kcal)',
        stats.averages.calories.toFixed(0),
        stats.goals.dailyCalories.toFixed(0),
        `${stats.achievement.calories}%`
      ],
      [
        'Protein (g)',
        stats.averages.protein.toFixed(1),
        stats.goals.dailyProtein.toFixed(0),
        `${stats.achievement.protein}%`
      ],
      [
        'Carbs (g)',
        stats.averages.carbs.toFixed(1),
        stats.goals.dailyCarbs.toFixed(0),
        `${stats.achievement.carbs}%`
      ],
      [
        'Fat (g)',
        stats.averages.fat.toFixed(1),
        stats.goals.dailyFat.toFixed(0),
        `${stats.achievement.fat}%`
      ],
    ],
    theme: 'grid',
    headStyles: {
      fillColor: [20, 82, 89],
      textColor: [255, 255, 255],
    },
    styles: {
      fontSize: 10,
    },
  });
  
  // Meal history
  yPos = (doc as any).lastAutoTable.finalY + 20;
  
  if (yPos > pageHeight - 60) {
    doc.addPage();
    yPos = 20;
  }
  
  doc.setFontSize(16);
  doc.text('Meal History', margin, yPos);
  
  yPos += 10;
  
  // Create meals table
  const mealRows = meals.slice(0, 50).map(meal => [
    new Date(meal.createdAt).toLocaleDateString(),
    meal.name,
    meal.mealType,
    meal.calories.toFixed(0),
    meal.protein.toFixed(1),
    meal.carbs.toFixed(1),
    meal.fat.toFixed(1),
  ]);
  
  autoTable(doc, {
    startY: yPos,
    head: [['Date', 'Food', 'Type', 'Cal', 'Protein', 'Carbs', 'Fat']],
    body: mealRows,
    theme: 'striped',
    headStyles: {
      fillColor: [20, 82, 89],
      textColor: [255, 255, 255],
    },
    styles: {
      fontSize: 8,
    },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 50 },
      2: { cellWidth: 20 },
    },
  });
  
  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by FitBuddy',
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  }
  
  // Save the PDF
  const fileName = `FitBuddy-Report-${timeRange}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

